[workspace]
resolver = "2"
members = [
  "crates/*",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
repository = "https://github.com/esmevane/oneiros"
license = "MIT"

[workspace.dependencies]
anstream = "0.6.21"
askama = "0.15"
axum = "0.8.8"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
clap-verbosity-flag = "3"
colorchoice-clap = "1.0.7"
data-encoding = "2"
directories = "5"
flate2 = "1"
http-body-util = "0.1.3"
hyper = { version = "1.8", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
inquire = "0.7"
oneiros-client = { path = "crates/oneiros-client" }
oneiros-db = { path = "crates/oneiros-db" }
oneiros-detect-project-name = { path = "crates/oneiros-detect-project-name" }
oneiros-fs = { path = "crates/oneiros-fs" }
oneiros-model = { path = "crates/oneiros-model" }
oneiros-outcomes = { path = "crates/oneiros-outcomes" }
oneiros-outcomes-derive = { path = "crates/oneiros-outcomes-derive" }
oneiros-service = { path = "crates/oneiros-service" }
oneiros-skill = { path = "crates/oneiros-skill" }
oneiros-templates = { path = "crates/oneiros-templates" }
oneiros-terminal = { path = "crates/oneiros-terminal" }
postcard = { version = "1", features = ["alloc"] }
pretty_assertions = "1"
prettyplease = "0.2"
proc-macro2 = "1"
quote = "1"
rusqlite = { version = "0.31", features = [
  "bundled",
  "functions",
  "serde_json",
  "uuid"
] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
service-manager = "0.10"
sha2 = "0.10"
syn = { version = "2", features = ["extra-traits", "full", "parsing"] }
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
tower = { version = "0.5.3", features = ["util"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
trybuild = "1"
uuid = { version = "1", features = ["serde", "v4", "v7"] }
whoami = "1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
