[package]
name = "oneiros-fs"
version.workspace = true
edition.workspace = true
description = "Common file system operations"
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
